site_name: Lenguaje de marcas
theme:
  name: 'material'
  palette:
      - scheme: default
      toggle:
          icon: material/brightness-7 
          name: Canvia a mode oscur

      - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Canvia a mode clar
  font:
    text: 'Roboto, sans-serif'
    code: 'Courier New, monospace'
  
  plugins:
     - search
     - page-to-pdf
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
  
  markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

  features:
    - content.code.copy

docs_dir: md
site_dir: docs
nav:
    - Home: index.md
    - UD.2:
      - Marcas de texto: MarcasTexto.md
    - About: Sobre-mi.md
extra_css:
  - css/extra.css

